#测试环境配置(配置项只包括不同项)
spring:
  datasource:
    url: jdbc:mysql://192.168.0.47:3306/mlsql_console2?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: ENC(NB2lV8hnECAOlNa5Dl+TVA==)
  redis:
    # 服务器IP地址
    host: biserver
    # 连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:

#白名单
ignore:
  urls:
    /api/**,
    /dealFilterChain/**,
    /swagger/**,
    /biApi/**,
    /schema/**,
    /dataSource/**