# 开发环境配置(配置项只包括环境不同项)
spring:
  datasource:
    url: jdbc:postgresql://192.168.0.212:5432/devp
    username: postgres
    password: ENC(jNMW0YbAdoH0eDWVEXxG+JnBpx24v9v6)
  redis:
    # 服务器IP地址
    host: biserver
    # 连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ENC(jNMW0YbAdoH0eDWVEXxG+JnBpx24v9v6)

#配置不需要认证的接口(白名单)
ignore:
  urls: /index/**,/login/**,/favicon.ico,*.html,/index,/dealFilterChain/reload,/user/**